# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number_opto', models.CharField(max_length=11)),
                ('article_number_supplier', models.CharField(max_length=200)),
                ('tft_brightness', models.IntegerField()),
                ('tft_contrast', models.CharField(max_length=200)),
                ('tft_color_amount', models.CharField(max_length=200)),
                ('tft_viewing_angle_u', models.IntegerField()),
                ('tft_viewing_angle_d', models.IntegerField()),
                ('tft_viewing_angle_l', models.IntegerField()),
                ('tft_viewing_angle_r', models.IntegerField()),
                ('tft_operating_temperature_min', models.FloatField()),
                ('tft_operating_temperature_max', models.FloatField()),
                ('tft_storage_temperature_min', models.FloatField()),
                ('tft_storage_temperature_max', models.FloatField()),
                ('tft_outline_h_mm', models.FloatField()),
                ('tft_outline_v_mm', models.FloatField()),
                ('tft_outline_d_mm', models.FloatField()),
                ('tft_active_area_h_mm', models.FloatField()),
                ('tft_active_area_v_mm', models.FloatField()),
                ('tft_touch_panel', models.BooleanField()),
                ('tft_in_production', models.BooleanField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modificated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
